name = "HEROBrowser"
version = "0.1.0"
type = "exec"
language = "cpp"

[sources]
dirs = ["src"]

[includes]
dirs = ["include"]
flags = ["-I/usr/include/freetype2"]  # Make sure FreeType headers are found

[build]
flags = ["-Wall", "-Wextra", "-Wpedantic", "-std=c++20"]
optimization = "2"
libs = ["SDL2", "SDL2_ttf", "freetype"]  # Link FreeType properly

[scripts]
prebuild = "echo 'Make sure FreeType, GLEW, GLFW are installed system-wide'"
postbuild = "echo 'Build complete - Run with: ./build/HEROBrowser'"
